# fly.toml app configuration file generated for epigen-webhook on 2025-05-18T23:26:07-04:00
#
# See https://fly.io/docs/reference/configuration/ for information about how to use this file.
#

app = 'epigen-webhook'
primary_region = 'gru'

[build]

[http_service]
  internal_port = 7860
  force_https = true
  auto_stop_machines = 'off'
  auto_start_machines = true
  min_machines_running = 1
  processes = ['app']

[[vm]]
  memory = '2gb'
  cpu_kind = 'shared'
  cpus = 1
